//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AACalc.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenu
    {
        public tblMenu()
        {
            this.tblRoleMenus = new HashSet<tblRoleMenu>();
        }
    
        public int MenuId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public int DisplayOrder { get; set; }
        public string CssClass { get; set; }
    
        public virtual ICollection<tblRoleMenu> tblRoleMenus { get; set; }
    }
}
