//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AACalc.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerson
    {
        public int PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DOB { get; set; }
        public string SpouseFirstName { get; set; }
        public string SpouseLastName { get; set; }
        public Nullable<System.DateTime> SpouseDOB { get; set; }
        public int EquipmentID { get; set; }
        public int SeatId { get; set; }
        public Nullable<int> YearOfCreditService { get; set; }
        public int AveFlyHours { get; set; }
        public Nullable<System.DateTime> AltRetireDate { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
